#!/usr/bin/env ruby

# Database
system 'dropdb <%= app_name %>'
system 'dropdb <%= app_name %>_test'
system 'dropuser <%= app_name %>'
system 'createuser -s <%= app_name %>'
system 'createdb <%= app_name %>'
system 'createdb <%= app_name %>_test'

system "rake db:schema:load"
system "rake db:migrate"
system "rake db:seed"
system "rake db:schema:load RAILS_ENV=test"
system "rake db:migrate RAILS_ENV=test"
system "rake db:seed RAILS_ENV=test"
