development: &default
  adapter: postgresql
  host: localhost
  database: <%= app_name %>
  encoding: unicode
  pool: <%%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= app_name %>
  password:

test:
  <<: *default
  database: <%= app_name %>_test
