#!/bin/sh -e

if [ $# -ne 2 ]; then
  echo 1>&2 "Usage: $0 <application name> <branch>"
  exit 1
fi

APP_NAME=$1

BRANCH=$2

REMOTE=$(git remote -v | awk '{print $2}' | grep "heroku" | grep "${APP_NAME}.git" | uniq)

PREV_WORKERS=$(heroku ps --app $APP_NAME | grep "^worker." | wc -l | xargs)

heroku maintenance:on --app $APP_NAME

heroku scale worker=0 --app $APP_NAME || true

git push -f $REMOTE $BRANCH:master

heroku run rake db:migrate db:seed --app $APP_NAME

heroku scale worker=$PREV_WORKERS --app $APP_NAME || true

heroku maintenance:off --app $APP_NAME
