#!/bin/sh -e

if [ $# -ne 1 ]; then
  echo 1>&2 "Usage: $0 <application name>"
  exit 1
fi

APP_NAME=$1

SHA_TO_DEPLOY=`git rev-parse HEAD`

REMOTE=$(git remote -v | awk '{print $2}' | grep "${APP_NAME}.git" | uniq)

PREV_WORKERS=$(heroku ps --app $APP_NAME | grep "^worker." | wc -l | xargs)

heroku maintenance:on --app $APP_NAME

heroku scale worker=0 --app $APP_NAME

git push -f $REMOTE $SHA_TO_DEPLOY:refs/heads/master

heroku run rake db:migrate db:seed --app $APP_NAME

heroku scale worker=$PREV_WORKERS --app $APP_NAME

heroku maintenance:off --app $APP_NAME
