#!/bin/bash

# <%= app_name %>
heroku config:set WEB_CONCURRENCY=2 --app <%= app_name %>
heroku config:set RAILS_MAX_THREADS=5 --app <%= app_name %>
heroku config:set REQUEST_TIMEOUT=10 --app <%= app_name %>
heroku config:set DATABASE_TIMEOUT=10 --app <%= app_name %>

# <%= app_name %>-staging
heroku config:set WEB_CONCURRENCY=2 --app <%= app_name %>-staging
heroku config:set RAILS_MAX_THREADS=5 --app <%= app_name %>-staging
heroku config:set REQUEST_TIMEOUT=10 --app <%= app_name %>-staging
heroku config:set DATABASE_TIMEOUT=10 --app <%= app_name %>-staging
