#!/usr/bin/env ruby
path = File.expand_path(File.dirname(__FILE__))

# Database
system 'dropdb <%= app_name %>'
system 'dropdb <%= app_name %>_test'
system 'dropuser <%= app_name %>'
system 'createuser -s <%= app_name %>'
system 'createdb <%= app_name %>'
system 'createdb <%= app_name %>_test'

# Hombrew
system 'bundle exec brewdle install'

# Git
system 'git remote add production git@heroku.com:<%= app_name %>.git'
system 'git remote add staging git@heroku.com:<%= app_name %>-staging.git'
