#!/usr/bin/env ruby
require 'pathname'

APP_ROOT = Pathname.new File.expand_path('../../',  __FILE__)

Dir.chdir APP_ROOT do
  puts 'Gems...'
  system 'bundle check || bundle install'

  puts 'Database...'
  system 'dropdb <%= app_name %>'
  system 'dropdb <%= app_name %>_test'
  system 'dropuser <%= app_name %>'
  system 'createuser -s <%= app_name %>'
  system 'createdb <%= app_name %>'
  system 'createdb <%= app_name %>_test'

  system 'rake dev:reset'

  puts 'Homebrew...'
  system 'brew tap Homebrew/bundle'
  system 'brew bundle'

  puts 'Git...'
  system 'git remote add production git@heroku.com:<%= app_name %>.git'
  system 'git remote add staging git@heroku.com:<%= app_name %>-staging.git'
end
